# .github/workflows/terraform-plan.yml

name: Terraform Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC — allows GitHub to request a token
      contents: read    # Allows reading repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Lambda package
        run: bash scripts/build.sh

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # REPLACE with your actual Account ID and role name
          role-to-assume: arn:aws:iam::273809175310:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

